In [69]:
# Import general useful packages
import numpy as np
import pandas as pd

# Import matplotlib for visualisations
import matplotlib.pyplot as plt
import matplotlib.cm as cm

# label encoding the data 
from sklearn.preprocessing import LabelEncoder

# Import all machine learning algorithms
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
import xgboost as xgb

# Import other useful subpackage
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

ModuleNotFoundError: No module named 'xgboost'

In [13]:
data_1 = pd.read_csv('C:\\Users\\Purnendu\\Desktop\\R Code\\Python\\Fraud Detection\\data.csv')

In [14]:
# For training data
print("data_1: {}".format(data_1.shape))
print("Null values present in fraud data: {}".format(data_1.isnull().values.any()))
## Output:
# Training Data: (5000, 71)
# Null values present in training data: False

data_1: (5000, 71)
Null values present in fraud data: False

In [15]:
data_1.head(5)

,f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,...,f62,f63,f64,f65,f66,f67,f68,f69,date_time,class
0,true,False,No,1,False,1,False,1,type_A,False,...,0,0,1,false,False,not_valid,1,160.0,2017-04-18T09:17:44.231,0
1,true,False,No,1,False,1,False,1,type_A,False,...,0,0,1,false,False,not_valid,1,159.0,2017-04-08T05:56:06.599,0
2,no_data,False,Yes,1,True,1,False,1,type_A,False,...,0,0,1,false,True,not_valid,1,118.0,2017-05-02T16:28:43.207,0
3,false,False,Yes,1,True,1,False,1,type_A,False,...,0,0,1,false,False,not_valid,1,155.0,2017-05-17T06:48:45.574,0
4,true,False,Yes,1,True,1,False,1,type_A,False,...,0,0,1,false,True,not_valid,1,125.0,2017-05-09T18:53:05.890,0

In [16]:
# Univariate Analysis
data_1.describe()

,f4,f6,f8,f18,f20,f21,f23,f25,f26,f27,...,f48,f52,f55,f58,f62,f63,f64,f68,f69,class
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,...,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.00000
mean,1.243600,1.155400,1.754200,1.074800,1.272000,548.471622,8.411000,1.101400,1.319600,1.249600,...,1296.837268,0.814454,1.058000,943.182078,1.774800,0.009200,0.689600,1.148200,1678.807733,0.10000
std,1.080228,0.767964,1.925753,0.336493,0.631265,888.582893,21.468457,0.666038,0.912153,4.793819,...,3389.653210,0.299089,5.017138,2683.703254,4.483225,0.101575,1.057864,1.782041,3234.937085,0.30003
min,1.000000,0.000000,1.000000,1.000000,1.000000,38.000000,0.100000,1.000000,1.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,38.000000,0.00000
25%,1.000000,1.000000,1.000000,1.000000,1.000000,109.965000,0.160000,1.000000,1.000000,1.000000,...,0.000000,0.570000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,145.500000,0.00000
50%,1.000000,1.000000,1.000000,1.000000,1.000000,184.995000,0.460000,1.000000,1.000000,1.000000,...,55.920000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,488.200000,0.00000
75%,1.000000,1.000000,2.000000,1.000000,1.000000,550.000000,2.770000,1.000000,1.000000,1.000000,...,963.805000,1.000000,1.000000,584.867500,2.000000,0.000000,1.000000,1.000000,1682.877500,0.00000
max,47.000000,36.000000,69.000000,5.000000,12.000000,5550.000000,99.000000,29.000000,19.000000,239.000000,...,50880.880000,1.000000,103.000000,46388.810000,66.000000,2.000000,24.000000,69.000000,48241.310000,1.00000

In [25]:
# label encoding the data 
le = LabelEncoder() 
  
data_1['f1']= le.fit_transform(data_1['f1']) 
data_1['f2']= le.fit_transform(data_1['f2'])
data_1['f3']= le.fit_transform(data_1['f3'])
data_1['f5']= le.fit_transform(data_1['f5'])
data_1['f7']= le.fit_transform(data_1['f7'])
data_1['f9']= le.fit_transform(data_1['f9'])
data_1['f10']= le.fit_transform(data_1['f10'])
data_1['f11']= le.fit_transform(data_1['f11'])
data_1['f12']= le.fit_transform(data_1['f12'])
data_1['f15']= le.fit_transform(data_1['f15'])
data_1['f16']= le.fit_transform(data_1['f16'])
data_1['f17']= le.fit_transform(data_1['f17'])
data_1['f19']= le.fit_transform(data_1['f19'])
data_1['f22']= le.fit_transform(data_1['f22'])
data_1['f24']= le.fit_transform(data_1['f24'])
data_1['f28']= le.fit_transform(data_1['f28'])
data_1['f29']= le.fit_transform(data_1['f29'])
data_1['f31']= le.fit_transform(data_1['f31'])
data_1['f32']= le.fit_transform(data_1['f32'])
data_1['f33']= le.fit_transform(data_1['f33'])
data_1['f34']= le.fit_transform(data_1['f34'])
data_1['f35']= le.fit_transform(data_1['f35'])
data_1['f37']= le.fit_transform(data_1['f37'])
data_1['f38']= le.fit_transform(data_1['f38'])
data_1['f39']= le.fit_transform(data_1['f39'])
data_1['f40']= le.fit_transform(data_1['f40'])
data_1['f41']= le.fit_transform(data_1['f41'])
data_1['f42']= le.fit_transform(data_1['f42'])
data_1['f43']= le.fit_transform(data_1['f43'])
data_1['f44']= le.fit_transform(data_1['f44'])
data_1['f45']= le.fit_transform(data_1['f45'])
data_1['f46']= le.fit_transform(data_1['f46'])
data_1['f49']= le.fit_transform(data_1['f49'])
data_1['f50']= le.fit_transform(data_1['f50'])
data_1['f51']= le.fit_transform(data_1['f51'])
data_1['f53']= le.fit_transform(data_1['f53'])
data_1['f54']= le.fit_transform(data_1['f54'])
data_1['f56']= le.fit_transform(data_1['f56'])
data_1['f57']= le.fit_transform(data_1['f57'])
data_1['f59']= le.fit_transform(data_1['f59'])
data_1['f60']= le.fit_transform(data_1['f60'])
data_1['f61']= le.fit_transform(data_1['f61'])
data_1['f65']= le.fit_transform(data_1['f65'])
data_1['f66']= le.fit_transform(data_1['f66'])
data_1['f67']= le.fit_transform(data_1['f67'])

In [47]:
#See the value after one hot ecdoing
data_1.head(5)

,f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,...,f62,f63,f64,f65,f66,f67,f68,f69,date_time,class
0,2,0,0,1,0,1,0,1,0,0,...,0,0,1,0,0,1,1,160.0,2017-04-18T09:17:44.231,0
1,2,0,0,1,0,1,0,1,0,0,...,0,0,1,0,0,1,1,159.0,2017-04-08T05:56:06.599,0
2,1,0,1,1,1,1,0,1,0,0,...,0,0,1,0,1,1,1,118.0,2017-05-02T16:28:43.207,0
3,0,0,1,1,1,1,0,1,0,0,...,0,0,1,0,0,1,1,155.0,2017-05-17T06:48:45.574,0
4,2,0,1,1,1,1,0,1,0,0,...,0,0,1,0,1,1,1,125.0,2017-05-09T18:53:05.890,0

In [65]:
# Get X and Y from data_1
x = data_1['class']
y = data_1.drop(columns = ['class','date_time'])

# Splitting the X and Y into the 
# Training set and Testing set 
from sklearn.model_selection import train_test_split 
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2, random_state = 123)

In [66]:
accuacy_scores = np.zeros(6)

#Support Vector classifier
clf = SVC().fit(x_train,y_train)
prediction = clf.predict(x_test)
accuracy_scores[0] = accuracy_score(y_test, prediction) * 100
print('Support Vector Classifier Accuracy: {}%'.format(accuracy_scores[0]))

ValueError: Expected 2D array, got 1D array instead:
array=[0. 0. 0. ... 0. 0. 0.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [60]:
# Applying PCA function on training 
# and testing set of X component 
from sklearn.decomposition import PCA 
  
pca = PCA(n_components = 2) 
  
#x_train = pca.fit_transform(x_train) 
#x_test = pca.transform(x_test) 
  
#explained_variance = pca.explained_variance_ratio_

ValueError: Expected 2D array, got 1D array instead:
array=[0. 0. 0. ... 0. 0. 0.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.